# Generated by Django 5.1.6 on 2026-09-11 11:20

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contact', 'Contact'), ('rental', 'Rental')], max_length=24, verbose_name='Type')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(max_length=64, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('rental_start_date', models.DateField(blank=True, null=True, verbose_name='Rental start date')),
                ('rental_end_date', models.DateField(blank=True, null=True, verbose_name='Rental end date')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('archived', 'Archived')], default='new', max_length=24, verbose_name='Status')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalLeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Comment')),
                ('lead', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='leads.lead')),
            ],
            options={
                'verbose_name': 'rental lead item',
                'verbose_name_plural': 'rental lead items',
            },
        ),
    ]
