# Generated by Django 5.1.6 on 2026-09-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalleaditem',
            name='rental_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_items', to='rental.rentalitem'),
        ),
    ]
