# Generated by Django 5.1.15 on 2026-10-08 23:55

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'категория проекта',
                'verbose_name_plural': 'категории проектов',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('video_file', models.FileField(blank=True, upload_to='project-videos/', verbose_name='Видео-файл')),
                ('external_video_url', models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка на MP4-файл.', verbose_name='Внешняя видео-ссылка')),
                ('short_caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись карточки')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('client', models.CharField(blank=True, max_length=255, verbose_name='Клиент')),
                ('production_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год')),
                ('role', models.CharField(blank=True, max_length=255, verbose_name='Роль/задача')),
                ('detail_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок detail')),
                ('detail_text', models.TextField(blank=True, verbose_name='Текст кейса')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=16, verbose_name='Статус')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка / превью видео')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['sort_order', '-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Скриншот')),
                ('project', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name': 'скриншот проекта',
                'verbose_name_plural': 'скриншоты проекта',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
