# Generated by Django 5.1.6 on 2026-09-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectgalleryimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'скриншот проекта', 'verbose_name_plural': 'скриншоты проекта'},
        ),
        migrations.AddField(
            model_name='project',
            name='video_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Превью видео'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Скриншот'),
        ),
    ]
