# Generated by Django 5.1.15 on 2026-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_default_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка на MP4-файл.', verbose_name='Внешняя видео-ссылка'),
        ),
    ]
