# Generated by Django 5.1.15 on 2026-10-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок контактов')),
                ('section_intro', models.TextField(blank=True, verbose_name='Описание блока контактов')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('telegram', models.CharField(blank=True, max_length=128, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=128, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=128, verbose_name='Youtube')),
                ('footer_legal_text', models.TextField(blank=True, verbose_name='Юридический текст в футере')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.TextField(verbose_name='Заголовок первого экрана')),
                ('hero_title_mobile', models.TextField(blank=True, verbose_name='Заголовок первого экрана на мобильных')),
                ('hero_text', models.TextField(verbose_name='Текст первого экрана')),
                ('hero_tags', models.CharField(blank=True, max_length=255, verbose_name='Строка тегов')),
                ('hero_video_file', models.FileField(blank=True, upload_to='showreel-videos/', verbose_name='Видео-файл showreel')),
                ('hero_video_url', models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка на MP4-файл.', verbose_name='Ссылка на основной showreel')),
                ('nav_about_label', models.CharField(blank=True, max_length=64, verbose_name='Меню: о нас')),
                ('nav_services_label', models.CharField(blank=True, max_length=64, verbose_name='Меню: услуги')),
                ('nav_projects_label', models.CharField(blank=True, max_length=64, verbose_name='Меню: проекты')),
                ('nav_rental_label', models.CharField(blank=True, max_length=64, verbose_name='Меню: аренда')),
                ('nav_contacts_label', models.CharField(blank=True, max_length=64, verbose_name='Меню: контакты')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка showreel')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MainPageSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок блока услуг')),
                ('services_intro', models.TextField(blank=True, verbose_name='Вводный текст услуг')),
                ('projects_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок портфолио')),
                ('projects_page_intro', models.TextField(blank=True, verbose_name='Описание страницы проектов')),
                ('projects_cta_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок призыва в проектах')),
                ('projects_cta_text', models.TextField(blank=True, verbose_name='Текст призыва в проектах')),
                ('rental_title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок аренды')),
                ('rental_search_label', models.CharField(blank=True, max_length=64, verbose_name='Подпись поиска аренды')),
                ('rental_page_intro', models.TextField(blank=True, verbose_name='Описание страницы аренды')),
                ('rental_cta_title', models.CharField(blank=True, max_length=160, verbose_name='Заголовок призыва в аренде')),
                ('rental_cta_text', models.TextField(blank=True, verbose_name='Текст призыва в аренде')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'заголовки',
                'verbose_name_plural': 'заголовки',
            },
        ),
    ]
