# Generated by Django 5.1.6 on 2026-09-11 11:20

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('telegram', models.CharField(blank=True, max_length=128, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=128, verbose_name='Instagram')),
                ('youtube', models.CharField(blank=True, max_length=128, verbose_name='Youtube')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details_text', wagtail.fields.RichTextField(blank=True, verbose_name='Реквизиты')),
                ('contacts_text', wagtail.fields.RichTextField(blank=True, verbose_name='Контакты в футере')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Заголовок hero')),
                ('hero_text', models.TextField(verbose_name='Текст hero')),
                ('hero_tags', models.CharField(blank=True, max_length=255, verbose_name='Строка тегов')),
                ('hero_video_url', models.URLField(blank=True, verbose_name='Hero video URL')),
                ('services_intro', models.TextField(blank=True, verbose_name='Вводный текст услуг')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
