# Generated by Codex on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsettings",
            name="form_email_label",
            field=models.CharField(default="Email", max_length=64, verbose_name="Label email"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_email_placeholder",
            field=models.CharField(default="email@mail.com", max_length=120, verbose_name="Placeholder email"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_message_label",
            field=models.CharField(default="Сообщение", max_length=64, verbose_name="Подпись сообщения"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_message_placeholder",
            field=models.CharField(default="Ваш текст", max_length=120, verbose_name="Подсказка сообщения"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_name_label",
            field=models.CharField(default="Имя", max_length=64, verbose_name="Label имени"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_name_placeholder",
            field=models.CharField(default="Как к вам обращаться?", max_length=120, verbose_name="Placeholder имени"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_phone_label",
            field=models.CharField(default="Телефон", max_length=64, verbose_name="Label телефона"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_phone_placeholder",
            field=models.CharField(default="+375-XX-XXXXXX", max_length=120, verbose_name="Placeholder телефона"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="form_title",
            field=models.CharField(default="СВЯЗАТЬСЯ С НАМИ", max_length=120, verbose_name="Заголовок формы связи"),
        ),
        migrations.AddField(
            model_name="contactsettings",
            name="section_title",
            field=models.CharField(default="КОНТАКТЫ", max_length=120, verbose_name="Заголовок контактов"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nav_about_label",
            field=models.CharField(default="О НАС", max_length=64, verbose_name="Навигация: о нас"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nav_contacts_label",
            field=models.CharField(default="КОНТАКТЫ", max_length=64, verbose_name="Навигация: контакты"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nav_projects_label",
            field=models.CharField(default="ПРОЕКТЫ", max_length=64, verbose_name="Навигация: проекты"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nav_rental_label",
            field=models.CharField(default="АРЕНДА", max_length=64, verbose_name="Навигация: аренда"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="nav_services_label",
            field=models.CharField(default="УСЛУГИ", max_length=64, verbose_name="Навигация: услуги"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="projects_title",
            field=models.CharField(default="НАШИ ПРОЕКТЫ", max_length=120, verbose_name="Заголовок проектов"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="rental_search_label",
            field=models.CharField(default="ПОИСК", max_length=64, verbose_name="Label поиска аренды"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="rental_title",
            field=models.CharField(default="АРЕНДА", max_length=120, verbose_name="Заголовок аренды"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_title",
            field=models.CharField(default="УСЛУГИ", max_length=120, verbose_name="Заголовок услуг"),
        ),
    ]
