# Generated by Django 5.1.6 on 2026-09-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_figma_copy_fields'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='projects_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='rental_search_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='rental_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='services_title',
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_email_label',
            field=models.CharField(default='Email', max_length=64, verbose_name='Подпись email'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_email_placeholder',
            field=models.CharField(default='email@mail.com', max_length=120, verbose_name='Подсказка email'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_message_label',
            field=models.CharField(default='Сообщение', max_length=64, verbose_name='Подпись сообщения'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_message_placeholder',
            field=models.CharField(default='Ваш текст', max_length=120, verbose_name='Подсказка сообщения'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_name_label',
            field=models.CharField(default='Имя', max_length=64, verbose_name='Подпись имени'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_name_placeholder',
            field=models.CharField(default='Как к вам обращаться?', max_length=120, verbose_name='Подсказка имени'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_phone_label',
            field=models.CharField(default='Телефон', max_length=64, verbose_name='Подпись телефона'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_phone_placeholder',
            field=models.CharField(default='+375-XX-XXXXXX', max_length=120, verbose_name='Подсказка телефона'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='form_title',
            field=models.CharField(default='СВЯЗАТЬСЯ С НАМИ', max_length=120, verbose_name='Заголовок формы связи'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Обложка showreel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(verbose_name='Текст первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=255, verbose_name='Заголовок первого экрана'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на основной showreel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_about_label',
            field=models.CharField(default='О НАС', max_length=64, verbose_name='Меню: о нас'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_contacts_label',
            field=models.CharField(default='КОНТАКТЫ', max_length=64, verbose_name='Меню: контакты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_projects_label',
            field=models.CharField(default='ПРОЕКТЫ', max_length=64, verbose_name='Меню: проекты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_rental_label',
            field=models.CharField(default='АРЕНДА', max_length=64, verbose_name='Меню: аренда'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_services_label',
            field=models.CharField(default='УСЛУГИ', max_length=64, verbose_name='Меню: услуги'),
        ),
        migrations.CreateModel(
            name='MainPageSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_title', models.CharField(default='УСЛУГИ', max_length=120, verbose_name='Заголовок блока услуг')),
                ('services_intro', models.TextField(blank=True, verbose_name='Вводный текст услуг')),
                ('projects_title', models.CharField(default='НАШИ ПРОЕКТЫ', max_length=120, verbose_name='Заголовок портфолио')),
                ('rental_title', models.CharField(default='АРЕНДА', max_length=120, verbose_name='Заголовок аренды')),
                ('rental_search_label', models.CharField(default='ПОИСК', max_length=64, verbose_name='Подпись поиска аренды')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'тексты секций главной',
                'verbose_name_plural': 'тексты секций главной',
            },
        ),
    ]
