# Generated by Django 5.1.6 on 2026-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_homepage_hero_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_title_mobile',
            field=models.TextField(blank=True, verbose_name='Заголовок первого экрана на мобильных'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.TextField(verbose_name='Заголовок первого экрана'),
        ),
    ]
