# Generated by Django 5.1.15 on 2026-10-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_site_business_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='section_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок контактов'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo или прямая ссылка на MP4-файл.', verbose_name='Ссылка на основной showreel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_about_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Меню: о нас'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_contacts_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Меню: контакты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_projects_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Меню: проекты'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_rental_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Меню: аренда'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_services_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Меню: услуги'),
        ),
        migrations.AlterField(
            model_name='mainpagesectionsettings',
            name='projects_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок портфолио'),
        ),
        migrations.AlterField(
            model_name='mainpagesectionsettings',
            name='rental_search_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='Подпись поиска аренды'),
        ),
        migrations.AlterField(
            model_name='mainpagesectionsettings',
            name='rental_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок аренды'),
        ),
        migrations.AlterField(
            model_name='mainpagesectionsettings',
            name='services_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='Заголовок блока услуг'),
        ),
    ]
