# Generated by Django 5.1.15 on 2026-10-08 23:55

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='RentalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/нет'), ('choice', 'Вариант')], max_length=16, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Единица измерения')),
                ('filterable', models.BooleanField(default=True, verbose_name='Показывать в фильтрах')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'характеристика аренды',
                'verbose_name_plural': 'характеристики аренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'раздел аренды',
                'verbose_name_plural': 'разделы аренды',
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Короткое описание')),
                ('search_aliases', models.TextField(blank=True, verbose_name='Поисковые варианты')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('detail_description', models.TextField(blank=True, verbose_name='Подробное описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('price_on_request', models.BooleanField(default=False, verbose_name='Цена по запросу')),
                ('price_unit', models.CharField(blank=True, max_length=64, verbose_name='Единица цены')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('unavailable', 'Недоступно')], default='available', max_length=24, verbose_name='Наличие')),
                ('publication_status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=16, verbose_name='Публикация')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rental.rentalcategory', verbose_name='Раздел')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное изображение')),
            ],
            options={
                'verbose_name': 'позиция аренды',
                'verbose_name_plural': 'позиции аренды',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RentalItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Изображение')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rental.rentalitem')),
            ],
            options={
                'verbose_name': 'изображение аренды',
                'verbose_name_plural': 'галерея аренды',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255, verbose_name='Текст')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Число')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Да/нет')),
                ('value_choice', models.CharField(blank=True, max_length=255, verbose_name='Вариант')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='rental.rentalattribute')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='rental.rentalitem')),
            ],
            options={
                'verbose_name': 'значение характеристики',
                'verbose_name_plural': 'значения характеристик',
                'unique_together': {('item', 'attribute')},
            },
        ),
    ]
