# Generated by Django 5.1.6 on 2026-09-11 11:20

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('choice', 'Choice')], max_length=16, verbose_name='Type')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Unit')),
                ('filterable', models.BooleanField(default=True, verbose_name='Use in filters')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'rental attribute',
                'verbose_name_plural': 'rental attributes',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RentalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'rental category',
                'verbose_name_plural': 'rental categories',
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Short description')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('detail_description', models.TextField(blank=True, verbose_name='Detail description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('price_on_request', models.BooleanField(default=False, verbose_name='Price on request')),
                ('price_unit', models.CharField(blank=True, max_length=64, verbose_name='Price unit')),
                ('video_file', models.FileField(blank=True, upload_to='rental-videos/', verbose_name='Video file')),
                ('external_video_url', models.URLField(blank=True, verbose_name='External video URL')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO description')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=24, verbose_name='Availability')),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16, verbose_name='Publication status')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rental.rentalcategory', verbose_name='Category')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main image')),
            ],
            options={
                'verbose_name': 'rental item',
                'verbose_name_plural': 'rental items',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RentalItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='rental.rentalitem')),
            ],
            options={
                'verbose_name': 'rental image',
                'verbose_name_plural': 'rental gallery',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RentalAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255, verbose_name='Text')),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Number')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Boolean')),
                ('value_choice', models.CharField(blank=True, max_length=255, verbose_name='Choice')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='rental.rentalattribute')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='rental.rentalitem')),
            ],
            options={
                'verbose_name': 'rental attribute value',
                'verbose_name_plural': 'rental attribute values',
                'unique_together': {('item', 'attribute')},
            },
        ),
    ]
