# Generated by Django 5.1.15 on 2026-09-15 09:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_pg_trgm'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalattribute',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'характеристика аренды', 'verbose_name_plural': 'характеристики аренды'},
        ),
        migrations.AlterModelOptions(
            name='rentalattributevalue',
            options={'verbose_name': 'значение характеристики', 'verbose_name_plural': 'значения характеристик'},
        ),
        migrations.AlterModelOptions(
            name='rentalcategory',
            options={'verbose_name': 'раздел аренды', 'verbose_name_plural': 'разделы аренды'},
        ),
        migrations.AlterModelOptions(
            name='rentalitem',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'позиция аренды', 'verbose_name_plural': 'позиции аренды'},
        ),
        migrations.AlterModelOptions(
            name='rentalitemimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'изображение аренды', 'verbose_name_plural': 'галерея аренды'},
        ),
        migrations.AlterField(
            model_name='rentalattribute',
            name='filterable',
            field=models.BooleanField(default=True, verbose_name='Показывать в фильтрах'),
        ),
        migrations.AlterField(
            model_name='rentalattribute',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rentalattribute',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='rentalattribute',
            name='type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('boolean', 'Да/нет'), ('choice', 'Вариант')], max_length=16, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='rentalattribute',
            name='unit',
            field=models.CharField(blank=True, max_length=32, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='rentalattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True, verbose_name='Да/нет'),
        ),
        migrations.AlterField(
            model_name='rentalattributevalue',
            name='value_choice',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='rentalattributevalue',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Число'),
        ),
        migrations.AlterField(
            model_name='rentalattributevalue',
            name='value_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='rentalcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='rentalcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='rentalcategory',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rental.rentalcategory', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='detail_description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='external_video_url',
            field=models.URLField(blank=True, verbose_name='Внешняя видео-ссылка'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='price_on_request',
            field=models.BooleanField(default=False, verbose_name='Цена по запросу'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='price_unit',
            field=models.CharField(blank=True, max_length=64, verbose_name='Единица цены'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=16, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('unavailable', 'Недоступно')], default='available', max_length=24, verbose_name='Наличие'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='video_file',
            field=models.FileField(blank=True, upload_to='rental-videos/', verbose_name='Видео-файл'),
        ),
        migrations.AlterField(
            model_name='rentalitemimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='rentalitemimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Изображение'),
        ),
    ]
