# Generated by Django 5.1.6 on 2026-09-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rentalattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='search_aliases',
            field=models.TextField(blank=True, verbose_name='Поисковые варианты'),
        ),
    ]
