# Generated by Django 5.1.6 on 2026-09-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_rentalitem_search_aliases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalitem',
            name='external_video_url',
        ),
        migrations.RemoveField(
            model_name='rentalitem',
            name='video_file',
        ),
    ]
