# Generated by Django 5.1.15 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_remove_rentalitem_external_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='publication_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='published', max_length=16, verbose_name='Публикация'),
        ),
    ]
